export default [
  {
    qryear:'2023',
    qrtitle:'First quarter',
    qrlinktexten:'First quarter english',
    qrlinktextfr:'First quarter french',
    qrlinken:'../../public/documets/first-dummy.pdf',
    qrlinkfr:'../../public/documets/first-dummy.pdf',
  },
  {
    qryear:'2023',
    qrtitle:'Second quarter',
    qrlinktexten:'Second quarter english',
    qrlinktextfr:'Second quarter french',
    qrlinken:'../../public/documets/second-dummy.pdf',
    qrlinkfr:'../../public/documets/second-dummy.pdf',
  },
  {
    qryear:'2023',
    qrtitle:'Third quarter',
    qrlinktexten:'Third quarter english',
    qrlinktextfr:'Third quarter french',
    qrlinken:'../../public/documets/third-dummy.pdf',
    qrlinkfr:'../../public/documets/third-dummy.pdf',
  },
  {
    qryear:'2023',
    qrtitle:'Forth quarter',
    qrlinktexten:'Forth quarter english',
    qrlinktextfr:'Forth quarter french',
    qrlinken:'../../public/documets/forth-dummy.pdf',
    qrlinkfr:'../../public/documets/forth-dummy.pdf',
  },
  {
    qryear:'2022',
    qrtitle:'First quarter',
    qrlinktexten:'First quarter english',
    qrlinktextfr:'First quarter french',
    qrlinken:'../../public/documets/first-dummy.pdf',
    qrlinkfr:'../../public/documets/first-dummy.pdf',
  },
  {
    qryear:'2022',
    qrtitle:'Second quarter',
    qrlinktexten:'Second quarter english',
    qrlinktextfr:'Second quarter french',
    qrlinken:'../../public/documets/second-dummy.pdf',
    qrlinkfr:'../../public/documets/second-dummy.pdf',
  },
  {
    qryear:'2022',
    qrtitle:'Third quarter',
    qrlinktexten:'Third quarter english',
    qrlinktextfr:'Third quarter french',
    qrlinken:'../../public/documets/third-dummy.pdf',
    qrlinkfr:'../../public/documets/third-dummy.pdf',
  },
  {
    qryear:'2022',
    qrtitle:'Forth quarter',
    qrlinktexten:'Forth quarter english',
    qrlinktextfr:'Forth quarter french',
    qrlinken:'../../public/documets/forth-dummy.pdf',
    qrlinkfr:'../../public/documets/forth-dummy.pdf',
  },
  {
    qryear:'2021',
    qrtitle:'First quarter',
    qrlinktexten:'First quarter english',
    qrlinktextfr:'First quarter french',
    qrlinken:'../../public/documets/first-dummy.pdf',
    qrlinkfr:'../../public/documets/first-dummy.pdf',
  },
  {
    qryear:'2021',
    qrtitle:'Second quarter',
    qrlinktexten:'Second quarter english',
    qrlinktextfr:'Second quarter french',
    qrlinken:'../../public/documets/second-dummy.pdf',
    qrlinkfr:'../../public/documets/second-dummy.pdf',
  },
  {
    qryear:'2021',
    qrtitle:'Third quarter',
    qrlinktexten:'Third quarter english',
    qrlinktextfr:'Third quarter french',
    qrlinken:'../../public/documets/third-dummy.pdf',
    qrlinkfr:'../../public/documets/third-dummy.pdf',
  },
  {
    qryear:'2021',
    qrtitle:'Forth quarter',
    qrlinktexten:'Forth quarter english',
    qrlinktextfr:'Forth quarter french',
    qrlinken:'../../public/documets/forth-dummy.pdf',
    qrlinkfr:'../../public/documets/forth-dummy.pdf',
  },
]